platform :ios, '11.0'
source 'https://github.com/abbeyjackson/CocoapodPOCPodspecs.git'

target 'ObjcPodApp' do

    use_modular_headers!

    pod 'SwiftFeatureFramework', '~> 0.2-NC'
    pod 'ObjcFeatureFramework', '~> 0.2-NC'

end
